#开放平台接口
OpenPlatform_API:
    #数据库相关配置
    DATABASE:
        host: 192.168.0.72
        username: webuser
        password: web123456
        #数据库表名
        database_merchant: MerchantCenter
        database_player: OpenPlatformPlayerCenter1
        #清数据时需要保留的数据表
        retaintable:  Strategy,GatewayConfig,PartnersConfig,TemplateAttr,TemplateItem,RechargeChannelConfig,RechargeChannelConfigTemplate,FirstLevelConfig,BillingTypeConfig,SecondLevelConfig,SdkConfigItem,cap.published,cap.received

    Redis:
        host: 10.8.26.230

        #需同步清除的玩家key关键字
        clearkeys_player: OpenPlatform:PlayerCenter:FindPlayerIdByAccount:*,OpenPlatform:PlayerCenter:FindPlayerIdByPhoneNo:*,OpenPlatform:PlayerCenter:FindPlayerIdByRegisterDevice:*
        clearkeys_merchant: OpenPlatform:MerchantCenter:IncrNumber:*,OpenPlatform:MerchantCenter:Product:*



    #商户
    Merchant:
        #商户创建
        MerchantCreate: http://192.168.3.26:8000/api/Merchant/CreateMerchant
        #商户编辑
        MerchantEdit: http://192.168.3.26:8000/api/Merchant/EditMerchant
        #商户查看
        MerchantGet: http://192.168.3.26:8000/api/Merchant/GetMerchant
        #商户列表
        MerchantList: http://192.168.3.26:8000/api/Merchant/MerchantList
    #管理员
    Admin:
        #新增管理员
        AdminAdd: http://192.168.3.26:8000/api/Admin/Add
        #编辑管理员
        AdminEdit: http://192.168.3.26:8000/api/Admin/Edit
        #查看管理员
        AdminGet: http://192.168.3.26:8000/api/Admin/
        #获取管理员列表
        AdminList: http://192.168.3.26:8000/api/Admin/list
    #渠道
    Channel:
        #新增渠道
        ChannelCreate: http://192.168.3.26:8000/api/Channel/Create
        #修改渠道
        ChannelModify: http://192.168.3.26:8000/api/Channel/Modify
        #获取渠道信息-传id拼接在url后
        ChannelGet: http://192.168.3.26:8000/api/Channel/
        #渠道列表
        ChannelList: http://192.168.3.26:8000/api/Channel/List
    #产品
    Product:
        #新增、修改、获取产品信息
        Product: http://192.168.3.26:8000/api/Product
        #产品列表
        ProductList: http://192.168.3.26:8000/api/Product/list
    #产品渠道
    ProductChannel:
        #产品渠道列表
        ProductChannelList: http://192.168.3.26:8000/api/ProductChannel/list
        #添加产品渠道
        ProductChannelCreate: http://192.168.3.26:8000/api/ProductChannel
        #获取产品渠道类型
        GetChannelType:  http://192.168.3.26:8000/api/ProductChannel/GetChannelTypeByCode
        #获取渠道名
        GetChannelName:  http://192.168.3.26:8000/api/ProductChannel/GetChannelName
        #检查AppId和渠道号
        CheckAppIdAndChannelNo: http://192.168.3.26:8000/api/ProductChannel/CheckAppIdAndChannelNo
    #分包
    ProductPackage:
        #分包列表
        ProductPackageList: http://192.168.3.26:8000/api/ProductPackage/list
        #添加分包
        ProductPackageCreate: http://192.168.3.26:8000/api/ProductPackage
        #获取分包号的简单信息
        ProductPackageSimpleInfo:  http://192.168.3.26:8000/api/ProductPackage/simple/info
    #账号
    User:
        #创建账号
        UserCreate: http://192.168.3.26:8000/api/User/Create
        #修改账号
        UserUpdate: http://192.168.3.26:8000/api/User/Update
        #账户列表
        UserList: http://192.168.3.26:8000/api/User/List
        #根据ID获取账户信息
        UserGet: http://192.168.3.26:8000/api/User/Get


    #验证码
    VerifyCode:
        #短信验证码
        sms: http://192.168.3.26:8001/api/VerifyCode/sms

    #玩家
    Player:
        #玩家注册
        Regist: http://192.168.3.26:8005/api/Player/Regist
        #玩家登录
        Login: http://192.168.3.26:8005/api/Player/Login
        #玩家转正
        Promote: http://192.168.3.26:8005/api/Player/Promote
        #获取玩家信息
        GetBaseInfo: http://192.168.3.26:8005/api/Player/GetBaseInfo
        #永久冻结账户
        Frozen: http://192.168.3.26:8005/api/Player/Frozen
        #解冻账户
        UnFrozen: http://192.168.3.26:8005/api/Player/UnFrozen
        #验证手机号是否注册
        CheckPhoneRegisted: http://192.168.3.26:8005/api/Player/CheckPhoneRegisted
        #异常登录-手机验证码
        LoginExceptionVertify_mobile: http://192.168.3.26:8005/api/Player/LoginExceptionVertify/mobile
        #财富充值
        Recharge: http://192.168.3.26:8005/api/Player/Recharge
        #财富消费
        Expenditure: http://192.168.3.26:8005/api/Player/Expenditure
        #重置密码
        ResetPassword: http://192.168.3.26:8005/api/Player/ResetPassword
        #绑定手机
        BindPhone: http://192.168.3.26:8005/api/Player/BindPhone
    #安全问题
    SecurityQuestion:
        #设置玩家问题
        PlayerQuestion: http://192.168.3.26:8005/api/SecurityQuestion/PlayerQuestion
        #玩家回答问题进度列表
        PlayerQuestionList: http://192.168.3.26:8005/api/SecurityQuestion/PlayerQuestionList
        #玩家问题判断
        Judge: http://192.168.3.26:8005/api/SecurityQuestion/Judge
    #后台用户中心
    User2:
        #用户列表
        UserList:  http://192.168.3.26:8005/api/User/List
        #获取用户详情
        UserDetail: http://192.168.3.26:8005/api/User/Detail
        #根据玩家获取玩家信息
        UserGet:  http://192.168.3.26:8005/api/User/Get
        #清空绑定手机
        ClearBindingPhone: http://192.168.3.26:8005/api/User/ClearBindingPhone
        #重置密码
        ResetPassword: http://192.168.3.26:8005/api/User/ResetPassword
        #修改用户状态
        UpdateState: http://192.168.3.26:8005/api/User/UpdateState
        #查询用户常用设备列表
        DeviceList: http://192.168.3.26:8005/api/User/device/common
        #查询/设置用户常用设备详情
        DeviceInfo: http://192.168.3.26:8005/api/User/device/common/


    #充值
    Pay:
        #下单
        Pay: http://192.168.3.45:8000/pay/pay






log:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

email:
    title: '接口自动化测试报告'
    message: '接口测试用例执行情况如附件所示，请查收！建议用Chrome浏览器打开~'
    receiver: 'yusi@qkagame.com;zhangtingting@qkagame.com;sulinzi@qkagame.com;zhouwei@qkagame.com;huangyu@qkagame.com;wangdeqiang@qkagame.com;leizhihui@qkagame.com;wangliangjian@qkagame.com'
    server: 'smtp.exmail.qq.com'
    sender: 'AutoTest@qkagame.com'
    password: 'Ys123456'

