URL1: http://wmanager.qkagame.net/Home/Index
URL: http://www.baidu.com

API_URL:
    recharge_pay: http://wpay.qkagame.net/recharge/pay
    InfoCheck: http://wapi.qkagame.net/api/Consortia/InfoCheck
    # sss: http://192.168.2.196/qka.cgi?target=relation&function=AddPromoteInfo
    # 钻石商城商品信息查询接口
    ProductList: http://wupdate.qkagame.net/api/Mall/Product/List
    # 钻石商城购买物品接口
    OrderCreate: http://wupdate.qkagame.net/api/Mall/Order/Create
    #平台服务：充值统一订单接口
    Pay: http://wpay2.qkagame.net/pay

log:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

email:
    title: '充值接口测试报告'
    message: '这是今天的测试报告，请查收！'
    receiver: 'yusi@qkagame.com'
    server: 'smtp.qq.com'
    sender: 'yusi@qkagame.com'
    password: 'yusi051925'

